-- Active: 1739013587682@@sql-server@1433@DATAWARE_HOUSE
USE master ;
IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'DATAWARE_HOUSE')
BEGIN
    DROP DATABASE DATAWARE_HOUSE;
END

CREATE DATABASE DATAWARE_HOUSE;
USE DATAWARE_HOUSE;
Go;
CREATE SCHEMA Bronz ;
GO;
CREATE SCHEMA Sliver ;
GO ;
CREATE SCHEMA Gold ;
GO ;



